/* eslint-disable camelcase */
// auth
export const LOADING = 'LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const CREATE_MESSAGES = 'CREATE_MESSAGES';
export const GET_ERRORS = 'GET_ERRORS';
export const LOADING_CHANGE_PASSWORD = 'LOADING_CHANGE_PASSWORD';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// employees
export const LOADING_CREATE_EMPLOYEE = 'LOADING_CREATE_EMPLOYEE';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_FAIL = 'CREATE_EMPLOYEE_FAIL';

export const GET_EMPLOYEE_SUCCESS = 'GET_EMPLOYEE_SUCCESS';
export const GET_EMPLOYEE_FAIL = 'GET_EMPLOYEE_FAIL';
export const GET_EMPLOYEE_LOADING = 'GET_EMPLOYEE_LOADING';
